apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: social-network
type: Opaque
stringData:
  JWT_SECRET: "H8iSudSwfv80TnZI7rS0YmGcO+CW1FZc6+L3KnAgmfE="
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
